name: EnvGuardian Check

on:
  pull_request:
  push:
    branches: [ main, develop_prod ]

jobs:
  envguardian:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create .env for CI
        run: |
          cat > .env <<EOF
          DATABASE_URL=dummy_database_url
          JWT_SECRET=dummy_jwt_secret
          VITE_API_URL=http://localhost:3000
          EOF

      - name: Run EnvGuardian Action
        uses: marcusjgb/envguardian-action@v1